services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: BRUTisgood!123
      MYSQL_DATABASE: quickquid
    ports:
      - "3306:3306"
    networks:
      - my-network

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/quickquid
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: BRUTisgood!123
    depends_on:
      - mysql
    networks:
      - my-network

  frontend:
    build:
      context: ../ibis-poc-frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - springboot-app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
